version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: bizfundraiser_db
    environment:
      POSTGRES_DB: bizfundraiser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bizfundraiser_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bizfundraiser_backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/bizfundraiser?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      NODE_ENV: production
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - bizfundraiser_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bizfundraiser_frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - bizfundraiser_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  bizfundraiser_network:
    driver: bridge